# Generated by Django 3.2.5 on 2022-04-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mail', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('holder_id', models.AutoField(primary_key=True, serialize=False)),
                ('holder_name', models.CharField(max_length=45)),
                ('holder_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_state', models.CharField(max_length=15)),
                ('place_city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_season_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='rateinfo.season')),
                ('section_year_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='rateinfo.year')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=127)),
                ('restaurant_holder_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='rateinfo.holder')),
                ('restaurant_place_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='rateinfo.place')),
                ('restaurant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='rateinfo.type')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=255)),
                ('comment_level', models.IntegerField()),
                ('comment_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='rateinfo.customer')),
                ('comment_restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='rateinfo.restaurant')),
                ('comment_section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='rateinfo.section')),
            ],
        ),
    ]
