# Generated by Django 3.2.5 on 2022-04-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_name']},
        ),
        migrations.AlterModelOptions(
            name='holder',
            options={'ordering': ['holder_name']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_state', 'place_city']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['restaurant_name', 'restaurant_holder_id']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section_year_id', 'section_season_id']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['year']},
        ),
    ]
