# Generated by Django 3.2.5 on 2022-04-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateinfo', '0002_auto_20220405_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_city',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_state',
            field=models.CharField(max_length=225),
        ),
    ]
