# Generated by Django 3.2.5 on 2022-04-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateinfo', '0003_auto_20220419_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_place', 'place_city']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_state',
            new_name='place_place',
        ),
    ]
